# Generated by Django 5.1.6 on 2025-02-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nom',
            new_name='classe',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='prenom',
        ),
    ]
