# Generated by Django 5.1.6 on 2025-02-27 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_nom_customuser_classe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='classe',
            field=models.ForeignKey(blank=True, help_text='Applicable uniquement si le rôle est Élève', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.classe'),
        ),
    ]
