# Generated by Django 5.1.6 on 2025-02-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_remove_cours_classes'),
        ('users', '0003_classe_alter_customuser_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classe',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
    ]
