# Generated by Django 5.1.6 on 2025-02-27 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_classe_delete_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('eleves', models.ManyToManyField(limit_choices_to={'role': 'eleve'}, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
