# Generated by Django 5.1.6 on 2025-02-27 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classe',
            field=models.ForeignKey(blank=True, help_text='Applicable uniquement si le rôle est Élève', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.classe'),
        ),
    ]
