# Generated by Django 5.1.6 on 2025-02-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='eleves',
        ),
    ]
