# Generated by Django 5.1.6 on 2025-02-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
        ('users', '0003_classe_alter_customuser_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='classes',
            field=models.ManyToManyField(related_name='cours', to='users.classe'),
        ),
    ]
