# Generated by Django 5.1.6 on 2025-02-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_cours_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='classes',
        ),
    ]
