# Generated by Django 5.1.6 on 2025-02-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_remove_cours_classes'),
        ('users', '0005_classe_alter_customuser_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='classes',
            field=models.ManyToManyField(related_name='cours', to='users.classe'),
        ),
    ]
